/**
 * Tests for gateway's local DID identity — the signer that produces the
 * three X-DID-* headers the Python verifier reconstructs.
 *
 * The critical test in this file is **the cross-language parity test**
 * (``cross-language contract`` suite below). It drives ``signPayload``
 * with a fixture that was hand-generated by the Python reference signer
 * (``bindu/utils/did/signature.py``) and asserts the resulting
 * signature is byte-for-byte identical. Any drift between the two
 * implementations — JSON separators, key order, encoding — surfaces as
 * a failed assertion here, BEFORE anyone tries to use the gateway to
 * talk to a real Bindu peer and gets a mysterious 403.
 *
 * To regenerate the fixture from scratch:
 *
 *   uv run python -c "
 *   import json, base58
 *   from nacl.signing import SigningKey
 *   seed = b'\\x00' * 32
 *   did  = 'did:bindu:test'
 *   body = b'{\"test\": \"value\"}'
 *   ts   = 1000
 *   payload = {'body': body.decode(), 'did': did, 'timestamp': ts}
 *   ps = json.dumps(payload, sort_keys=True)
 *   sk = SigningKey(seed)
 *   print('signature:', base58.b58encode(sk.sign(ps.encode()).signature).decode())
 *   print('pubkey:', base58.b58encode(bytes(sk.verify_key)).decode())
 *   "
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest"
import {
  deriveAgentId,
  loadLocalIdentity,
  pythonSortedJson,
  sanitizeAuthor,
  signPayload,
} from "../../src/bindu/identity/local"

// ---------------------------------------------------------------------------
// Canonical fixture — generated by bindu/utils/did/signature.py with the
// inputs below. Do not change any of these values without also regenerating
// the signature from the Python side (see module docstring).
// ---------------------------------------------------------------------------

const FIXTURE = {
  // 32-byte seed (all zeros — deterministic, easy to reproduce)
  seed: new Uint8Array(32),
  did: "did:bindu:test",
  body: '{"test": "value"}',
  timestamp: 1000,
  expected: {
    // Exact bytes Python signs. Default separators in json.dumps have
    // SPACES after `:` and `,` — callers MUST match, not JS defaults.
    payloadStr:
      '{"body": "{\\"test\\": \\"value\\"}", "did": "did:bindu:test", "timestamp": 1000}',
    signatureBase58:
      "3SfU4VPTHLbzZzCn17ZqU6y2tnzHQbdo2nnXQr6XZXk34XgyzwSKRrCYEWRmmGXrV39mdkyhTsy5oasfTpNuqyM2",
    publicKeyBase58: "4zvwRjXUKGfvwnParsHAS3HuSVzV5cA4McphgmoCtajS",
  },
} as const

// ---------------------------------------------------------------------------
// pythonSortedJson — the single most likely place to drift from Python
// ---------------------------------------------------------------------------

describe("pythonSortedJson — matches Python json.dumps(sort_keys=True)", () => {
  it("produces SPACES after colons and commas", () => {
    expect(pythonSortedJson({ a: 1, b: 2 })).toBe('{"a": 1, "b": 2}')
  })

  it("sorts object keys alphabetically", () => {
    expect(pythonSortedJson({ b: 2, a: 1, c: 3 })).toBe(
      '{"a": 1, "b": 2, "c": 3}',
    )
  })

  it("sorts recursively at every nesting level", () => {
    expect(pythonSortedJson({ outer: { z: 1, a: 2 }, inner: [1, 2] })).toBe(
      '{"inner": [1, 2], "outer": {"a": 2, "z": 1}}',
    )
  })

  it("matches Python's exact payload string for the fixture", () => {
    const actual = pythonSortedJson({
      body: FIXTURE.body,
      did: FIXTURE.did,
      timestamp: FIXTURE.timestamp,
    })
    expect(actual).toBe(FIXTURE.expected.payloadStr)
  })

  it("handles null, boolean, string, number primitives", () => {
    expect(pythonSortedJson(null)).toBe("null")
    expect(pythonSortedJson(true)).toBe("true")
    expect(pythonSortedJson(false)).toBe("false")
    expect(pythonSortedJson(42)).toBe("42")
    expect(pythonSortedJson("hello")).toBe('"hello"')
  })

  it("escapes strings the same way JSON.stringify does", () => {
    // A body containing quotes — the main edge case for signature payloads.
    expect(pythonSortedJson('he said "hi"')).toBe('"he said \\"hi\\""')
  })

  it("throws on non-finite numbers rather than emitting invalid JSON", () => {
    expect(() => pythonSortedJson(Infinity)).toThrow()
    expect(() => pythonSortedJson(NaN)).toThrow()
  })
})

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

describe("sanitizeAuthor", () => {
  it("replaces @ with _at_ and . with _", () => {
    expect(sanitizeAuthor("raahul.dutta@example.com")).toBe(
      "raahul_dutta_at_example_com",
    )
  })

  it("is a no-op for already-sanitized input", () => {
    expect(sanitizeAuthor("simplename")).toBe("simplename")
  })
})

describe("deriveAgentId", () => {
  it("produces a UUID-formatted string", () => {
    const key = new Uint8Array(32).fill(0)
    const id = deriveAgentId(key)
    expect(id).toMatch(/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/)
  })

  it("is deterministic — same public key → same agent id", () => {
    const key = new Uint8Array(32).fill(7)
    expect(deriveAgentId(key)).toBe(deriveAgentId(key))
  })

  it("different keys → different agent ids", () => {
    expect(deriveAgentId(new Uint8Array(32).fill(1))).not.toBe(
      deriveAgentId(new Uint8Array(32).fill(2)),
    )
  })
})

// ---------------------------------------------------------------------------
// CROSS-LANGUAGE CONTRACT — the load-bearing test
// ---------------------------------------------------------------------------

describe("signPayload — cross-language contract with Python signer", () => {
  it("produces byte-for-byte the same signature Python produces", async () => {
    const headers = await signPayload({
      seed: FIXTURE.seed,
      did: FIXTURE.did,
      body: FIXTURE.body,
      timestamp: FIXTURE.timestamp,
    })
    expect(headers["X-DID"]).toBe(FIXTURE.did)
    expect(headers["X-DID-Timestamp"]).toBe(String(FIXTURE.timestamp))
    // This is the assertion that catches any future drift:
    expect(headers["X-DID-Signature"]).toBe(FIXTURE.expected.signatureBase58)
  })

  it("produces the same signature when called twice (Ed25519 is deterministic)", async () => {
    const a = await signPayload({
      seed: FIXTURE.seed,
      did: FIXTURE.did,
      body: FIXTURE.body,
      timestamp: FIXTURE.timestamp,
    })
    const b = await signPayload({
      seed: FIXTURE.seed,
      did: FIXTURE.did,
      body: FIXTURE.body,
      timestamp: FIXTURE.timestamp,
    })
    expect(a).toEqual(b)
  })
})

// ---------------------------------------------------------------------------
// loadLocalIdentity — env loading + validation
// ---------------------------------------------------------------------------

const TEST_ENV = "TEST_BINDU_GATEWAY_DID_SEED"

function setSeedEnv(b64: string | undefined) {
  if (b64 === undefined) delete process.env[TEST_ENV]
  else process.env[TEST_ENV] = b64
}

describe("loadLocalIdentity", () => {
  afterEach(() => setSeedEnv(undefined))

  it("throws a clear error when the env var is missing", () => {
    setSeedEnv(undefined)
    expect(() =>
      loadLocalIdentity({
        author: "ops@example.com",
        name: "gateway",
        seedEnvVar: TEST_ENV,
      }),
    ).toThrow(/TEST_BINDU_GATEWAY_DID_SEED is not set/)
  })

  it("throws a clear error when the seed is the wrong length", () => {
    setSeedEnv(Buffer.from(new Uint8Array(16)).toString("base64"))
    expect(() =>
      loadLocalIdentity({
        author: "ops@example.com",
        name: "gateway",
        seedEnvVar: TEST_ENV,
      }),
    ).toThrow(/32 bytes/)
  })

  it("loads a valid seed and builds a DID + signer", async () => {
    setSeedEnv(Buffer.from(FIXTURE.seed).toString("base64"))
    const id = loadLocalIdentity({
      author: "ops@example.com",
      name: "gateway",
      seedEnvVar: TEST_ENV,
    })

    expect(id.did).toMatch(/^did:bindu:ops_at_example_com:gateway:/)
    expect(id.publicKeyBase58).toBe(FIXTURE.expected.publicKeyBase58)

    // Signer works — produce a signature for a dummy body, verify headers
    const headers = await id.sign("hello", 1000)
    expect(headers["X-DID"]).toBe(id.did)
    expect(headers["X-DID-Timestamp"]).toBe("1000")
    expect(headers["X-DID-Signature"]).toMatch(/^[1-9A-HJ-NP-Za-km-z]+$/) // base58
  })

  it("timestamp defaults to Math.floor(Date.now() / 1000) when omitted", async () => {
    setSeedEnv(Buffer.from(FIXTURE.seed).toString("base64"))
    const id = loadLocalIdentity({
      author: "a",
      name: "b",
      seedEnvVar: TEST_ENV,
    })
    const before = Math.floor(Date.now() / 1000)
    const headers = await id.sign("hello")
    const after = Math.floor(Date.now() / 1000)
    const ts = Number(headers["X-DID-Timestamp"])
    expect(ts).toBeGreaterThanOrEqual(before)
    expect(ts).toBeLessThanOrEqual(after + 1)
  })
})
